name: PrTarget New

on:
  pull_request_target:

jobs:
  generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - id: comment
      shell: bash
      run: |
        echo "I am very new."
        echo " ${{ github.event.action }} "
        echo "${{ github.ref }}"
        ls -la .
        ls -la .git
